reg_weekend = {0: 'Free Practice 1', 1: 'Free Practice 2', 2: 'Free Practice 3', 3: 'Qualifying', 4: 'Race'}
sprint_weekend = {0: 'Free Practice 1', 1: 'Qualifying', 2: 'Free Practice 2', 3: 'Sprint', 4: 'Race'}
name_conv = {'Saudi Arabia': 'Saudi Arabian', 'Australia': 'Australian', 'Spain': 'Spanish', 'Canada': 'Canadian',
             'Great Britain': 'British', 'Austria': 'Austrian', 'France': 'French', 'Hungary': 'Hungarian',
             'Belgium': 'Belgian', 'Netherlands': 'Dutch', 'Italy': 'Italian', 'Russia': 'Russian', 'Japan': 'Japanese',
             'Mexico': 'Mexican', 'Brazil': 'Brazilian'}
svg_bypass = {'Dutch': 'Zandvoort.svg',
              'Abu Dhabi': 'Yas_Marina_Circuit_2021_new_Formula_One_layout_proposal_08_07_2021.svg'}
circuit_maps = {'Abu Dhabi': 'https://i.ibb.co/VxynD5d/Abu-Dhabi-Grand-Prix.png',
                'Australian': 'https://i.ibb.co/hDF7p6n/Australian-Grand-Prix.png',
                'Austrian': 'https://i.ibb.co/KzsK3q2/Austrian-Grand-Prix.png',
                'Azerbaijan': 'https://i.ibb.co/n3CV25q/Azerbaijan-Grand-Prix.png',
                'Bahrain': 'https://i.ibb.co/37MmWQD/Bahrain-Grand-Prix.png',
                'Belgian': 'https://i.ibb.co/5rN850T/Belgian-Grand-Prix.png',
                'Brazilian': 'https://i.ibb.co/sJNF7gp/Brazilian-Grand-Prix.png',
                'British': 'https://i.ibb.co/gFc1Dzg/British-Grand-Prix.png',
                'Canadian': 'https://i.ibb.co/G2j3TSn/Canadian-Grand-Prix.png',
                'Dutch': 'https://i.ibb.co/jLQM44N/Dutch-Grand-Prix.png',
                'Emilia Romagna': 'https://i.ibb.co/JxPJBG9/Emilia-Romagna-Grand-Prix.png',
                'French': 'https://i.ibb.co/VwZ04bH/French-Grand-Prix.png',
                'Hungarian': 'https://i.ibb.co/4svqj9q/Hungarian-Grand-Prix.png',
                'Italian': 'https://i.ibb.co/1nSSJ7R/Italian-Grand-Prix.png',
                'Japanese': 'https://i.ibb.co/94zBBcb/Japanese-Grand-Prix.png',
                'Mexican': 'https://i.ibb.co/Ss5Vzp3/Mexican-Grand-Prix.png',
                'Miami': 'https://i.ibb.co/wh7Fk95/Miami-Grand-Prix.png',
                'Monaco': 'https://i.ibb.co/HhKZY5v/Monaco-Grand-Prix.png',
                'Saudi Arabian': 'https://i.ibb.co/QDMdWQC/Saudi-Arabian-Grand-Prix.png',
                'Singapore': 'https://i.ibb.co/kDLhcsc/Singapore-Grand-Prix.png',
                'Spanish': 'https://i.ibb.co/Kzxg6rW/Spanish-Grand-Prix.png',
                'United States': 'https://i.ibb.co/p05QGxk/United-States-Grand-Prix.png'}